### ISSUE TITLE
No sound is captured, l10n errors

### ISSUE THREAD

**Issue by skarmoutsosv** [gillesdegottex/fmit#34]
There are localization problems which make FMIT unusable.
More specifically if the capture device name is in greek, no sound is captured.
Please take a look at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802924

**Comment by gillesdegottex** [comment]
Actually I think the device name "default" shouldn't be translated because it is a technical description of a device (e.g alsa_input.pci-0000_00_1). Thus I fixed all the translations to translate "default" by itself.

However, since someone might (willingly or not) translate it, I added a security to have always the translation of "default" as the exact string "default" to be used in the implementations.

Tell me if this is fixed now.
